version: "3.9"

services:

  stats-postgres:
    image: postgres:15
    container_name: stats-postgres
    environment:
      POSTGRES_DB: stats_db
      POSTGRES_USER: stats_user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5437:5432"
    volumes:
      - stats_pg_data:/var/lib/postgresql/data
    networks:
      - repair-network

  postgres:
    image: postgres:15
    container_name: users-postgres
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: users_user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - users_pg_data:/var/lib/postgresql/data
    networks:
      - repair-network

  warehouse-postgres:
    image: postgres:15
    container_name: warehouse-postgres
    environment:
      POSTGRES_DB: warehouse_db
      POSTGRES_USER: warehouse_user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5434:5432"
    volumes:
      - warehouse_pg_data:/var/lib/postgresql/data
    networks:
      - repair-network

  orders-postgres:
    image: postgres:15
    container_name: orders-postgres
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: orders_user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5435:5432"
    volumes:
      - orders_pg_data:/var/lib/postgresql/data
    networks:
      - repair-network

  support-postgres:
    image: postgres:15
    container_name: support-postgres
    environment:
      POSTGRES_DB: support_db
      POSTGRES_USER: support_user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5436:5432"
    volumes:
      - support_pg_data:/var/lib/postgresql/data
    networks:
      - repair-network

  users-service:
    build: ./users-service
    container_name: users-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - repair-network

  support-service:
    build: ./support-service
    container_name: support-service
    ports:
      - "8084:8084"
    depends_on:
      - support-postgres
    networks:
      - repair-network

  warehouse-service:
    build: ./warehouse-service
    container_name: warehouse-service
    ports:
      - "8082:8082"
    depends_on:
      - warehouse-postgres
    networks:
      - repair-network

  stats-service:
    build: ./stats-service
    container_name: stats-service
    ports:
      - "8085:8085"
    depends_on:
      - stats-postgres
      - kafka
    networks:
      - repair-network

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"  
    depends_on:
      - users-service
    networks:
      - repair-network

  orders-service:
    build: ./orders-service
    container_name: orders-service
    ports:
      - "8083:8083"
    depends_on:
      - orders-postgres
    networks:
      - repair-network

  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_NUM_PARTITIONS: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    volumes:
      - kafka_data:/var/lib/kafka/data

    networks:
      - repair-network

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - repair-network

volumes:
  stats_pg_data:
  users_pg_data:
  warehouse_pg_data:
  orders_pg_data:
  support_pg_data:
  kafka_data:

networks:
  repair-network:
    driver: bridge