server:
  port: 8083
  address: 0.0.0.0 

spring:
  application:
    name: orders
  datasource:
    url: jdbc:postgresql://orders-postgres:5432/orders_db
    username: orders_user
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


resilience4j:

  retry:
    instances:
      warehouseRetry:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.ResourceAccessException
          - java.io.IOException
      supportRetry:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.ResourceAccessException
          - java.io.IOException

  circuitbreaker:
    instances:
      warehouseCircuit:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
      supportCircuit:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s

  timelimiter:
    instances:
      warehouseTimeout:
        timeout-duration: 2s

#logging:
#  level:
#    org.hibernate.SQL: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: W3C

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

services:
  warehouse:
    url: http://warehouse-service:8082
  users:
    url: http://users-service:8081