##server:
##  port: 8080
##  address: 0.0.0.0
##
##spring:
##  main:
##    web-application-type: reactive
##
##  cloud:
##    gateway:
##      server:
##        webflux:
##          routes:
##            - id: admin-users
##              uri: http://users-service:8081
##              predicates:
##                - Path=/api/crud/users/**
##
##            - id: admin-branches
##              uri: http://users-service:8081
##              predicates:
##                - Path=/api/crud/branches/**
##
##            - id: auth
##              uri: http://users-service:8081
##              predicates:
##                - Path=/api/auth/**
##          httpclient:
##            connect-timeout: 5000
##            response-timeout: 10s
##      globalcors:
##            add-to-simple-url-handler-mapping: true   # ВОТ ЭТО КРИТИЧНО
##            cors-configurations:
##                  '[/**]':
##                    allowedOriginPatterns:
##                        - "*"
##                    allowedMethods:
##                        - GET
##                        - POST
##                        - PUT
##                        - DELETE
##                        - OPTIONS
##                    allowedHeaders:
##                        - "*"
##                    allowCredentials: true
##
##
##security:
##  jwt:
##    public-key: |
##      -----BEGIN PUBLIC KEY-----
##      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2wW4Csl9ytzuyw8oQbfR
##      Fjs8rxv9a72sufeLPXfHaqNh1q2VCZjCiCtjozVpBDQreW0SfOI/nfVnnYDHNy0Q
##      2jAizLQPUPmKtzq8dy9cUPCfIZS22SW7P9r02jf0InbGoNRXhNAU2n2q+OuhVawc
##      jQGcSTaDXVLqaayKxMPHTo75BZlhr+4ZlYFcwBUbhoQ+px+iWQRK/4z6QSu23zo6
##      pES+pfFuqIzuUR/5s6DTr9mn0bNEl67pjYWRMrDj0zVwF1TlmggWmP2xIlxECXTA
##      HqFj2Z5VHIhK/FJZyLXfkI6ChXeRkB1U7cMlLUV4aH5Sa/+Q2ppjlZx198NhF5SH
##      kQIDAQAB
##      -----END PUBLIC KEY-----
##
##logging:
##  level:
##    org.springframework.cloud.gateway: DEBUG
#server:
#  port: 8080
#  address: 0.0.0.0
#
#spring:
#  main:
#    web-application-type: reactive
#
#  cloud:
#    gateway:
#      server:
#        webflux:
#
#          routes:
#            - id: admin-users
#              uri: http://users-service:8081
#              predicates:
#                - Path=/api/crud/users/**
#
#            - id: admin-branches
#              uri: http://users-service:8081
#              predicates:
#                - Path=/api/crud/branches/**
#
#            - id: auth
#              uri: http://users-service:8081
#              predicates:
#                - Path=/api/auth/**
#
#            - id: orders
#              uri: http://orders-service:8083
#              predicates:
#                - Path=/api/orders/**
#
#            - id: warehouse-parts
#              uri: http://warehouse-service:8082
#              predicates:
#                - Path=/api/parts/**
#
#            - id: warehouse-pricing
#              uri: http://warehouse-service:8082
#              predicates:
#                - Path=/api/pricing-policies/**
#
#            - id: warehouse-stock
#              uri: http://warehouse-service:8082
#              predicates:
#                - Path=/api/stock/**
#
#          httpclient:
#            connect-timeout: 5000
#            response-timeout: 10s
#
#          globalcors:
#            add-to-simple-url-handler-mapping: true
#            cors-configurations:
#              '[/**]':
#                allowedOrigins:
#                  - "http://localhost:3000"
#                allowedMethods:
#                  - GET
#                  - POST
#                  - PUT
#                  - PATCH
#                  - DELETE
#                  - OPTIONS
#                allowedHeaders:
#                  - "*"
#                allowCredentials: true
#
#security:
#  jwt:
#    public-key: |
#      -----BEGIN PUBLIC KEY-----
#      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2wW4Csl9ytzuyw8oQbfR
#      Fjs8rxv9a72sufeLPXfHaqNh1q2VCZjCiCtjozVpBDQreW0SfOI/nfVnnYDHNy0Q
#      2jAizLQPUPmKtzq8dy9cUPCfIZS22SW7P9r02jf0InbGoNRXhNAU2n2q+OuhVawc
#      jQGcSTaDXVLqaayKxMPHTo75BZlhr+4ZlYFcwBUbhoQ+px+iWQRK/4z6QSu23zo6
#      pES+pfFuqIzuUR/5s6DTr9mn0bNEl67pjYWRMrDj0zVwF1TlmggWmP2xIlxECXTA
#      HqFj2Z5VHIhK/FJZyLXfkI6ChXeRkB1U7cMlLUV4aH5Sa/+Q2ppjlZx198NhF5SH
#      kQIDAQAB
#      -----END PUBLIC KEY-----
#
#logging:
#  level:
#    org.springframework.cloud.gateway: DEBUG

server:
  port: 8080
  address: 0.0.0.0

spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      server:
        webflux:

          routes:

            # =========================
            # USERS SERVICE
            # =========================

            - id: auth
              uri: http://users-service:8081
              predicates:
                - Path=/api/auth/**

            - id: admin-users
              uri: http://users-service:8081
              predicates:
                - Path=/api/crud/users/**

            - id: admin-branches
              uri: http://users-service:8081
              predicates:
                - Path=/api/crud/branches/**

            # =========================
            # ORDERS SERVICE
            # =========================

            - id: orders
              uri: http://orders-service:8083
              predicates:
                - Path=/api/orders/**

            # =========================
            # WAREHOUSE SERVICE
            # =========================

            - id: warehouse-parts
              uri: http://warehouse-service:8082
              predicates:
                - Path=/api/parts/**

            - id: warehouse-pricing
              uri: http://warehouse-service:8082
              predicates:
                - Path=/api/pricing-policies/**

            - id: warehouse-services
              uri: http://warehouse-service:8082
              predicates:
                - Path=/api/services/**

            - id: warehouse-stock
              uri: http://warehouse-service:8082
              predicates:
                - Path=/api/stock/**

            - id: support-requests
              uri: http://support-service:8084
              predicates:
                - Path=/api/support-requests/**

          httpclient:
            connect-timeout: 5000
            response-timeout: 10s

          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:3000"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: true

security:
  jwt:
    public-key: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2wW4Csl9ytzuyw8oQbfR
      Fjs8rxv9a72sufeLPXfHaqNh1q2VCZjCiCtjozVpBDQreW0SfOI/nfVnnYDHNy0Q
      2jAizLQPUPmKtzq8dy9cUPCfIZS22SW7P9r02jf0InbGoNRXhNAU2n2q+OuhVawc
      jQGcSTaDXVLqaayKxMPHTo75BZlhr+4ZlYFcwBUbhoQ+px+iWQRK/4z6QSu23zo6
      pES+pfFuqIzuUR/5s6DTr9mn0bNEl67pjYWRMrDj0zVwF1TlmggWmP2xIlxECXTA
      HqFj2Z5VHIhK/FJZyLXfkI6ChXeRkB1U7cMlLUV4aH5Sa/+Q2ppjlZx198NhF5SH
      kQIDAQAB
      -----END PUBLIC KEY-----

logging:
  level:
    org.springframework.cloud.gateway: DEBUG