server:
  port: 8084
  address: 0.0.0.0 

spring:
  application:
    name: support
  datasource:
    url: jdbc:postgresql://support-postgres:5432/support_db
    username: support_user
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: W3C

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans